# **Data Wrangling Lab**

In this assignment you will be performing data wrangling.

## Objectives

In this lab you will perform the following:

-   Identify duplicate values in the dataset.

-   Remove duplicate values from the dataset.

-   Identify missing values in the dataset.

-   Impute the missing values in the dataset.

-   Normalize data in the dataset.

<hr>

## Hands on Lab

Import pandas module.

In [129]:
import pandas as pd

Load the dataset into a dataframe.

In [130]:
df = pd.read_csv("https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DA0321EN-SkillsNetwork/LargeData/m1_survey_data.csv")

In [131]:
df.head()

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,...,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
0,4,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
1,9,I am a developer by profession,Yes,Once a month or more often,The quality of OSS and closed source software ...,Employed full-time,New Zealand,No,Some college/university study without earning ...,"Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,NaN,23.0,Man,No,Bisexual,White or of European descent,No,Appropriate in length,Neither easy nor difficult
2,13,I am a developer by profession,Yes,Less than once a month but more than once per ...,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,United States,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)","Computer science, computer engineering, or sof...",...,Somewhat more welcome now than last year,Tech articles written by other developers;Cour...,28.0,Man,No,Straight / Heterosexual,White or of European descent,Yes,Appropriate in length,Easy
3,16,I am a developer by profession,Yes,Never,The quality of OSS and closed source software ...,Employed full-time,United Kingdom,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)",NaN,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,26.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Neither easy nor difficult
4,17,I am a developer by profession,Yes,Less than once a month but more than once per ...,The quality of OSS and closed source software ...,Employed full-time,Australia,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,29.0,Man,No,Straight / Heterosexual,Hispanic or Latino/Latina;Multiracial,No,Appropriate in length,Easy

## Finding duplicates

In this section you will identify duplicate values in the dataset.

 Find how many duplicate rows exist in the dataframe.

In [132]:
df.duplicated().value_counts()

False    11398
True       154
Name: count, dtype: int64

In [133]:
df['Respondent'].duplicated().value_counts()

Respondent
False    11398
True       154
Name: count, dtype: int64

## Removing duplicates

Remove the duplicate rows from the dataframe.

In [134]:
df.drop_duplicates(inplace=True)

Verify if duplicates were actually dropped.

In [135]:
df.duplicated().value_counts()

False    11398
Name: count, dtype: int64

In [136]:
df['EdLevel'].isnull().sum() #112 blank rows

112

In [137]:
df['Country'].isnull().sum() #0

0

In [138]:
#majority category under employment
df['Employment'].value_counts().idxmax()

'Employed full-time'

In [139]:
df['UndergradMajor'].value_counts().idxmin()

'A health science (ex. nursing, pharmacy, radiology)'

## Finding Missing values

Find the missing values for all columns.

In [140]:
df.isnull().sum().sort_values(ascending=False)

BlockchainIs          2610
CodeRevHrs            2426
BlockchainOrg         2322
MiscTechWorkedWith    2182
SONewContent          1965
                      ...
JobSeek                  0
MainBranch               0
LastHireDate             0
CurrencySymbol           0
Respondent               0
Length: 85, dtype: int64

Find out how many rows are missing in the column 'WorkLoc'

In [141]:
df['WorkLoc'].isnull().sum()

32

## Imputing missing values

Find the  value counts for the column WorkLoc.

In [142]:
df['WorkLoc'].value_counts()

WorkLoc
Office                                            6806
Home                                              3589
Other place, such as a coworking space or cafe     971
Name: count, dtype: int64

Identify the value that is most frequent (majority) in the WorkLoc column.

In [143]:
#make a note of the majority value here, for future reference
#Office

Impute (replace) all the empty rows in the column WorkLoc with the value that you have identified as majority.

In [144]:
#df['WorkLoc'] = df['WorkLoc'].fillna('Office')
df.fillna({'WorkLoc':'Office'}, inplace=True)

C:\Users\fotip\AppData\Local\Temp\ipykernel_18696\1129622796.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['WorkLoc'].fillna('Office', inplace=True)

After imputation there should ideally not be any empty rows in the WorkLoc column.

Verify if imputing was successful.

In [145]:
df['WorkLoc'].isnull().sum()

0

## Normalizing data

There are two columns in the dataset that talk about compensation.

One is "CompFreq". This column shows how often a developer is paid (Yearly, Monthly, Weekly).

The other is "CompTotal". This column talks about how much the developer is paid per Year, Month, or Week depending upon his/her "CompFreq". 

This makes it difficult to compare the total compensation of the developers.

In this section you will create a new column called 'NormalizedAnnualCompensation' which contains the 'Annual Compensation' irrespective of the 'CompFreq'.

Once this column is ready, it makes comparison of salaries easy.

<hr>

List out the various categories in the column 'CompFreq'

In [146]:
df['CompFreq'].unique()

array(['Yearly', 'Monthly', 'Weekly', nan], dtype=object)

In [147]:
df['CompFreq'].value_counts()

CompFreq
Yearly     6073
Monthly    4788
Weekly      331
Name: count, dtype: int64

In [148]:
df['CompFreq'].isnull().sum()

206

Create a new column named 'NormalizedAnnualCompensation'  
If the CompFreq is Yearly then use the exising value in CompTotal  
If the CompFreq is Monthly then multiply the value in CompTotal with 12 (months in an year)  
If the CompFreq is Weekly then multiply the value in CompTotal with 52 (weeks in an year)

In [178]:
df['CompTotal'][df['CompFreq']=='Weekly']

12         2000.0
13        22000.0
46        67800.0
76       137000.0
135           NaN
           ...
11401     90000.0
11407      2250.0
11417     65000.0
11430     90000.0
11443      2880.0
Name: CompTotal, Length: 331, dtype: float64

In [179]:
import numpy as np
df["NormalizedAnnualCompensation"] = np.NaN

df.loc[df['CompFreq']=='Yearly', "NormalizedAnnualCompensation"] = df['CompTotal']
df.loc[df['CompFreq']=='Monthly', "NormalizedAnnualCompensation"] = df['CompTotal']*12
df.loc[df['CompFreq']=='Weekly', "NormalizedAnnualCompensation"] = df['CompTotal']*52

In [180]:
df[['CompTotal','CompFreq',"NormalizedAnnualCompensation"]][df['CompFreq']=='Weekly']

       CompTotal CompFreq  NormalizedAnnualCompensation
12        2000.0   Weekly                      104000.0
13       22000.0   Weekly                     1144000.0
46       67800.0   Weekly                     3525600.0
76      137000.0   Weekly                     7124000.0
135          NaN   Weekly                           NaN
...          ...      ...                           ...
11401    90000.0   Weekly                     4680000.0
11407     2250.0   Weekly                      117000.0
11417    65000.0   Weekly                     3380000.0
11430    90000.0   Weekly                     4680000.0
11443     2880.0   Weekly                      149760.0

[331 rows x 3 columns]

In [184]:
df["NormalizedAnnualCompensation"].median()
#should be 100K

98000.0

In [186]:
df["NormalizedAnnualCompensation"].mean()

6018878.494021689

In [187]:
df["NormalizedAnnualCompensation"].isnull().sum()

609

In [ ]:
#df["NormalizedAnnualCompensation"].fillna()

In [ ]:
df['ConvertedComp'].sort_values(ascending=False)

7937     2000000.0
3319     2000000.0
7257     2000000.0
5172     2000000.0
740      2000000.0
           ...
11519          NaN
11524          NaN
11531          NaN
11534          NaN
11551          NaN
Name: ConvertedComp, Length: 11398, dtype: float64

In [ ]:
df['ConvertedComp'].median()

57745.0

In [ ]:
df['ConvertedComp'].mean()

131596.7316197316

In [ ]:
df['ConvertedComp'].isnull().sum()

816

In [ ]:
cc_df = df['ConvertedComp'].fillna(df['ConvertedComp'].median())

In [ ]:
cc_df.mean() #lowered , of course

126309.57483769082